1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

# 1
empty_array = np.empty((2,2))
print("Empty array of dimension 2x2: \n",empty_array,"\n")

2. Initialize an all one array with size 4X2.



In [3]:
ones_array = np.ones((4,2))
print("All one array with size 4x2: \n",ones_array,"\n")

All one array with size 4x2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



3.Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
full_array = np.full((3,2), 7)
print("Array filled with given value : \n",full_array,"\n")

4.Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [4]:
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference Array: ", zeros_like_array)


Zeros Array with Same Shape as Reference Array:  [[0 0 0]
 [0 0 0]]


5.Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [6]:
ones_like_array = np.ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference Array: ", ones_like_array)


Ones Array with Same Shape as Reference Array:  [[1 1 1]
 [1 1 1]]


6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [7]:
new_list=[1,2,3,4]
new_array=np.array(new_list)
print("List: ", new_list);
print("Numpy Array: ", new_array);

List:  [1, 2, 3, 4]
Numpy Array:  [1 2 3 4]


Problem 2

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [8]:
#1
import numpy as np
array_in_given_range = np.arange(10,50)
print("Array with values ranging from 10 to 49: \n",array_in_given_range,"\n")


Array with values ranging from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 



In [9]:

#2
three_by_three_matrix = np.arange(0,9)
reshaped_matrix = three_by_three_matrix.reshape(3,3)
print("Reshaped matrix: \n",reshaped_matrix,"\n")

#3
identity_matrix = np.eye(3)
print("Identity matrix: \n",identity_matrix,"\n")

#4
random_array = np.random.random(30)
mean_of_array = random_array.mean()
print("Mean of random array: ",mean_of_array,"\n")


#5
ten_by_ten_array = np.random.random((10,10))
print("10x10 array: ",ten_by_ten_array, "\n")
max_value = ten_by_ten_array.max()
min_value = ten_by_ten_array.min()
print("Maximum value: ",max_value,"\n")
print("Minimum value: ",min_value,"\n")

#6
zero_array = np.zeros(10)
print("Zero array: \n", zero_array, "\n")
zero_array[4]=1;
print("Zero array after replacing 5th element with 1: \n", zero_array, "\n")


#7
arr = np.array([1,2,0,0,4,0])
print("Original array: \n", arr, "\n")
reversed_arr = arr[::-1]
print("Reversed array: \n", reversed_arr, "\n")


#8
unique_array = np.ones((5,5))
unique_array[1:-1, 1:-1]=0
print("Array with ones on border and zeros elsewhere: \n",unique_array,"\n")


#9
check_board_array = np.zeros((8,8))
check_board_array[0::2, 0::2] = 1
check_board_array[1::2, 1::2] = 1
print("Checkboard pattern: \n",check_board_array, "\n")

Reshaped matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Mean of random array:  0.45999751689665314 

10x10 array:  [[0.0477194  0.58648342 0.23475348 0.41121632 0.99393357 0.93000269
  0.18810436 0.74858542 0.81651889 0.26347939]
 [0.62038285 0.61621145 0.72653612 0.82574403 0.64960502 0.13579618
  0.7114752  0.57370266 0.31512146 0.22160026]
 [0.02105677 0.24356244 0.90691807 0.12126823 0.78759013 0.91758812
  0.70342144 0.6883031  0.36840135 0.65754929]
 [0.40259858 0.20797773 0.72372699 0.08831007 0.95392799 0.59010393
  0.67200316 0.30911487 0.36158345 0.16360604]
 [0.2343677  0.23149742 0.46618847 0.17999243 0.36982691 0.70670328
  0.8830246  0.84457501 0.56603531 0.2644813 ]
 [0.70682952 0.19809995 0.20967836 0.39593977 0.65890761 0.68389577
  0.47737179 0.91557492 0.01570285 0.4988345 ]
 [0.72414019 0.11485799 0.83663669 0.27923327 0.22416261 0.82382264
  0.19065013 0.6108181  0.3114055  0.80867473]
 [0.05730346 0.51556501 0.485

Problem 3

In [10]:
#Problem 3
# For the following arrays:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
add=x+y
print(add)
print("------")
# 2. Subtract the two array.
sub=v-w
print(sub)
print("-------")
# 3. Multiply the array with any integers of your choice.
multi=x*2
print(multi)
print("--------")
# 4. Find the square of each element of the array.
square=np.square(x)
print(square)
print("--------")
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_product1=np.dot(v,w)
dot_product2=np.dot(x,v)
dot_product3=np.dot(x,y)
print(dot_product1)
print(dot_product2)
print(dot_product3)
print("---------")
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)
print("--------")

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenated x and v:\n", concat_xv)
except Exception as e:
    print("Error:", e)


[[ 6  8]
 [10 13]]
------
[-2 -2]
-------
[[ 2  4]
 [ 6 10]]
--------
[[ 1  4]
 [ 9 25]]
--------
219
[29 77]
[[19 22]
 [50 58]]
---------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
--------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


problem 4

In [11]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I (Identity Matrix)
# Inverse of A
A_inv = np.linalg.inv(A)

# A . A⁻¹
result = np.dot(A, A_inv)

print("A * A⁻¹:\n", result)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)

# Check if AB = BA
is_equal = np.array_equal(AB, BA)
print("\nIs AB equal to BA? ", is_equal)

# 3. Prove (AB)ᵀ = BᵀAᵀ

# (AB)ᵀ
AB_transpose = np.transpose(AB)

#Bᵀ and Aᵀ
BT = np.transpose(B)
AT = np.transpose(A)

# BᵀAᵀ
BT_AT = np.dot(BT, AT)

print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)

# Check if (AB)ᵀ = BᵀAᵀ
is_transpose_equal = np.array_equal(AB_transpose, BT_AT)
print("\nIs (AB)ᵀ equal to BᵀAᵀ? ", is_transpose_equal)

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?  False

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

Is (AB)ᵀ equal to BᵀAᵀ?  True


4.2 Experiment: How Fast is Numpy?
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [12]:
import time

python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise Addition: \n")
start_at = time.time()
sum1 = [python_list1[i] + python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
sum2 = array1 + array2
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Element-wise Addition: 

Time taken using python lists:  0.020756959915161133 seconds.

Time taken using NumPy arrays: 0.0043561458587646484 seconds





2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [13]:
python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise Multiplicatio: \n")
start_at = time.time()
product1 = [python_list1[i] * python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
product2 = array1*array2
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Element-wise Multiplicatio: 

Time taken using python lists:  0.016365528106689453 seconds.

Time taken using NumPy arrays: 0.004472494125366211 seconds


In [16]:
python_list1=[i for i in range(1,100000)]
python_list2=[j for j in range(1,100000)]

print("Element-wise dot product: \n")
start_at = time.time()
product1 = [python_list1[i] * python_list2[i] for i in range(len(python_list1))]
end_at = time.time()
print("Time taken using python lists: ", end_at-start_at, "seconds.\n")


array1 = np.arange(1_000_000)
array2 = np.arange(1_000_000)

start_at = time.time()
product2 = np.dot(array1, array2)
end_at = time.time()
print("Time taken using NumPy arrays:", end_at - start_at, "seconds")

Element-wise dot product: 

Time taken using python lists:  0.0180819034576416 seconds.

Time taken using NumPy arrays: 0.001293182373046875 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [17]:
import time

matrix1 = [[i for i in range(100)] for _ in range(100)]
matrix2 = [[j for j in range(100)] for _ in range(100)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds")
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds.")

Time taken by Python Lists: 0.12892 seconds
Time taken by numpy: 0.00140 seconds
Time taken for matrix multiplication using NumPy arrays: 0.0014014244079589844 seconds.
